{% set name = "aws-c-sdkutils" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 493cbed4fa57e0d4622fcff044e11305eb4fc12445f32c8861025597939175fc

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-sdkutils", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake >=3.9
    - ninja-base
  host:
    - aws-c-common 0.12.4

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-sdkutils${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/sdkutils/sdkutils.h  # [unix]
    - if not exist %LIBRARY_INC%\aws\sdkutils\sdkutils.h exit 1          # [win]
    - if not exist %LIBRARY_BIN%\aws-c-sdkutils.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-sdkutils
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C.
  description: |
    C99 library implementing AWS SDK specific utilities.
    Includes utilities for ARN parsing, reading AWS profiles, etc...
  doc_url: https://github.com/awslabs/aws-c-sdkutils
  dev_url: https://github.com/awslabs/aws-c-sdkutils

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
