{% set name = "aws-c-sdkutils" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f21d770e6a41e82e658a92607a1df3c13bf905071843b8d6dfaaefc784102cd6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-sdkutils", max_pin="x.x.x") }}

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-common

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-sdkutils${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/sdkutils/sdkutils.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\sdkutils\\sdkutils.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-sdkutils.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-sdkutils
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This is a module for the AWS SDK for C.

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
